### PR TITLE
Animalpose plugin

### PR DESCRIPTION
**Pull request by bertoni9**
* Add animalpose plugin into openpifapaf core
* Add commands to download dataset
* Clean structure

### CODE REVIEW

**Comment by svenkreiss** [comment]
Hey @bertoni9 , the CI issue is about the format of the notebooks. Can you run `cd guide; python nb_cell_tags.py` again to reformat the notebooks?

**Review by svenkreiss — COMMENTED** [review]
Thanks @bertoni.

Before merging, can you please change the folder structure and make it similar to the other plugins / in the guide:
* There should not be an `animalpose` folder inside an `animalpose` folder. The module should be accessible under `openpifpaf.plugins.animalpose` and data preprocessing scripts and train/val split files can be inside `openpifpaf/plugins/animalpose/scripts`.
* The guide has currently folders by type. I.e. all the notebooks are in the root and all the images are in a folder called images. Please follow that for now. I do agree that it might be time to split by headline but then it would have to be an `animalpose` folder that contains both the animalpose notebook and its associated images and we'd have to do that for all documents. Let's not change that right now.

**Comment by bertoni9** [comment]
Hi @svenkreiss, thank you for the comments. 
I agree on the structure and I am working on the refactoring. Only one thing: how would you like the preprocessing script to be called? Before it was _python3 -m animalpose.voc_to_coco_ and the data folder was inside the animalpose directory, while now it's not in a package directory anymore. I think also the car preprocessing may need to be updated.
Thanks,
Lorenzo

**Comment by svenkreiss** [comment]
Hi @bertoni9 . Please make it callable with `python3 -m openpifpaf.plugins.animalpose.scripts.voc_to_coco` or `python3 -m openpifpaf.plugins.animalpose.voc_to_coco`. The data should sit in `data-animalpose` in the root directory. Thanks.

**Comment by bertoni9** [comment]
Perfect, let me know if this works. Thanks

**Review by svenkreiss — COMMENTED** [review]
Excellent! This looks great. Just one last thing before the merge (sorry): remove the image of the animal skeleton. I don't want that in version control after the merge. Can you re-use the code from the coco or wholebody guide page to create this within the notebook?

**Comment by bertoni9** [comment]
Hi @svenkreiss, ready on my side. Thanks!

**Comment by svenkreiss** [comment]
Excellent! New readme looks great!

**Pull request merged**
